version: 0.1.{build}
branches:
  only:
  - master
configuration:
- Release
before_build:
- ps: nuget restore src/condep-dsl-operations-azure.sln
build:
  project: src\condep-dsl-operations-azure.sln
os: Visual Studio 2015
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
